name: dice_games
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  oimo_physics: ^0.0.4
  vector_math: ^2.1.4
  three_js: ^0.1.2
  css:
    git:
      url: https://github.com/LimbitlessSolutionsInc/css.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  three_js_core:
    path: ../../development/three_js/packages/three_js_core

flutter:
  uses-material-design: true
  assets:
    - assets/dice_highres_red.glb